/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pzin;

import com.zaxxer.hikari.HikariConfig;

public class App {
    public static void main(String... args) {
        HikariConfig config = new HikariConfig();
        System.out.println(config);
    }
}